version: 0.1
phases:
  install:
    commands:
      - 'touch .npmignore'
      - 'npm install -g gatsby'
      - 'npm install -g yarn'
    pre_build:
      commands:
        - 'yarn install'
    build:
      commands:
        - 'npm run build'
    post_build:
      commands:
        -'aws s3 sync "public/" "s3://www.cameronbillings.com" --delete --acl "public-read"'
articfacts:
  files:
    - '**/*'

